[lab_computers]
192.168.137.[1:253]

[lab_computers:vars]
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_user=.\User
ansible_password=anjos2014
ansible_port=5985
